version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_asac
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: asac
      MYSQL_USER: asac
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    image: gradle:7.6-jdk17
    container_name: spring_app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/asac?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    command: gradle bootRun --no-daemon

volumes:
  mysql_data: