version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_asac
    environment:
      POSTGRES_DB: asac
      POSTGRES_USER: asac
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: gradle:7.6-jdk17
    container_name: spring_app
    volumes:
      - ./spring-app:/app
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/asac
    command: gradle bootRun --no-daemon

  metrics-exporter:
    build: ./metrics-exporter
    container_name: metrics_exporter
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=asac
      - DB_PASSWORD=1234
      - DB_NAME=asac

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - app
      - metrics-exporter

volumes:
  postgres_data: