version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_asac
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: asac
      MYSQL_USER: asac
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    image: gradle:7.6-jdk17
    container_name: spring_app
    volumes:
      - ./spring-app:/app
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/asac?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    command: gradle bootRun --no-daemon

  metrics-exporter:
    build: ./metrics-exporter
    container_name: metrics_exporter
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - app
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=asac
      - DB_PASSWORD=1234
      - DB_NAME=asac

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - app
      - metrics-exporter

volumes:
  mysql_data: